#!/bin/sh
# 
# The purpose of this script is to step in if no version of the "redo" build
# system is installed on your system to interpret the files that (Makefile-like)
# build the PlomRogue system: ./all.do, ./roguelike-client.do and
# ./roguelike-server.do.
# 
# If a version of "redo" is installed on your system and in your $PATH, just run
# "redo roguelike-client", "redo roguelike-server" or plain "redo" (to build
# both via all.do). Otherwise, run this very script with the very same
# arguments. It uses parts of a basic "redo" implementation written by Nils
# Dagsson Moskopp a.k.a. erlehmann, snapshots of which are stored in
# build/redo_scripts/. For details on this version, see:
# - <http://news.dieweltistgarnichtso.net/bin/redo.html>
# - <http://news.dieweltistgarnichtso.net/bin/redo-ifchange.html>
#
# This "redo" implementation may experience trouble on OS X systems, see
# <https://github.com/plomlompom/plomrogue/issues/2#issuecomment-50972436> for a
# workaround.

echo "non-redo stuff (preparing for future Python port sans redo needs):"
echo "Building library for server's Python variant with mere shell one-liner."
./compile-server.sh

export PATH=$PATH:$PWD/build/redo_scripts
redo "$@"
